"""initial migration

Revision ID: a485377f5593
Revises: 
Create Date: 2026-01-02 23:31:43.154681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a485377f5593'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('brand_id')
    )
    op.create_index(op.f('ix_brands_brand_id'), 'brands', ['brand_id'], unique=False)
    op.create_table('engine_types',
    sa.Column('engine_type_id', sa.Integer(), nullable=False),
    sa.Column('engine_type_name', sa.String(), nullable=True),
    sa.Column('cylinders', sa.Integer(), nullable=True),
    sa.Column('engine_size', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.PrimaryKeyConstraint('engine_type_id')
    )
    op.create_index(op.f('ix_engine_types_engine_type_id'), 'engine_types', ['engine_type_id'], unique=False)
    op.create_table('fuel_types',
    sa.Column('fuel_type_id', sa.Integer(), nullable=False),
    sa.Column('fuel_type_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('fuel_type_id')
    )
    op.create_index(op.f('ix_fuel_types_fuel_type_id'), 'fuel_types', ['fuel_type_id'], unique=False)
    op.create_table('oil_quality',
    sa.Column('oil_id', sa.Integer(), nullable=False),
    sa.Column('oil_grade', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('oil_id')
    )
    op.create_index(op.f('ix_oil_quality_oil_id'), 'oil_quality', ['oil_id'], unique=False)
    op.create_table('transmissions',
    sa.Column('transmission_id', sa.Integer(), nullable=False),
    sa.Column('transmission_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('transmission_id')
    )
    op.create_index(op.f('ix_transmissions_transmission_id'), 'transmissions', ['transmission_id'], unique=False)
    op.create_table('vehicle_classes',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_index(op.f('ix_vehicle_classes_class_id'), 'vehicle_classes', ['class_id'], unique=False)
    op.create_table('models',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_index(op.f('ix_models_model_id'), 'models', ['model_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('engine_type_id', sa.Integer(), nullable=True),
    sa.Column('fuel_type_id', sa.Integer(), nullable=True),
    sa.Column('transmission_id', sa.Integer(), nullable=True),
    sa.Column('oil_id', sa.Integer(), nullable=True),
    sa.Column('tyre_size', sa.String(), nullable=True),
    sa.Column('fuel_efficiency_highway', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('fuel_efficiency_combined', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['vehicle_classes.class_id'], ),
    sa.ForeignKeyConstraint(['engine_type_id'], ['engine_types.engine_type_id'], ),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_types.fuel_type_id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ),
    sa.ForeignKeyConstraint(['oil_id'], ['oil_quality.oil_id'], ),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmissions.transmission_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_index(op.f('ix_vehicles_vehicle_id'), 'vehicles', ['vehicle_id'], unique=False)
    op.create_table('maintenance_costs',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('yearly_cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('recorded_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_maintenance_costs_record_id'), 'maintenance_costs', ['record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_costs_record_id'), table_name='maintenance_costs')
    op.drop_table('maintenance_costs')
    op.drop_index(op.f('ix_vehicles_vehicle_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_models_model_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_vehicle_classes_class_id'), table_name='vehicle_classes')
    op.drop_table('vehicle_classes')
    op.drop_index(op.f('ix_transmissions_transmission_id'), table_name='transmissions')
    op.drop_table('transmissions')
    op.drop_index(op.f('ix_oil_quality_oil_id'), table_name='oil_quality')
    op.drop_table('oil_quality')
    op.drop_index(op.f('ix_fuel_types_fuel_type_id'), table_name='fuel_types')
    op.drop_table('fuel_types')
    op.drop_index(op.f('ix_engine_types_engine_type_id'), table_name='engine_types')
    op.drop_table('engine_types')
    op.drop_index(op.f('ix_brands_brand_id'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
